
volumes:
  postgres_data:

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    command: postgres -c 'work_mem=5GB' -c 'shared_buffers=5GB'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data